### ISSUE TITLE
Theme docs need tweaking for $ syntax and extensions via state not view

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [codemirror/website#12]
The sample theme in the [Styles and Themes section](https://github.com/codemirror/website/blob/master/site/docs/guide/index.md#styles-and-themes) of the docs doesn't work for me with @codemirror/view v0.17.7. So far as I can tell it needs to pass the extension via state not directly to the view and be updated for the $ prefix.

I got it working with this code:

```javascript
let view = new EditorView({
  state: EditorState.create({
    extensions: EditorView.theme({
      $content: { color: "orange" }
    }), 
  })
);
```

Some of the surrounding text might need tweaking to explain the $ prefix too.

Thanks for the really helpful overview docs 😄

**Comment by marijnh** [comment]
Thanks for spotting that. Patch 44a4e23c271a7 should help.
