### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by marijnh** [codemirror/website#13]
These need to be written, at the very least:

 - [x] Creating a language mode
 - [x] Dynamic configuration
 - [x] Collaborative editing
 - [x] Internationalization
 - [x] Decorating
 - [x] Tooltip/panel use
 - [x] Autocompletion
 - [x] Linting
 - [x] Custom autocompletion
 - [x] Creating/using highlighters
 - [x] Writing a theme
 - [x] Nested parsing (including a template-style language)

**Comment by marijnh** [comment]
Add https://codemirror.net/6/examples/lang-package/

**Comment by marijnh** [comment]
Added https://codemirror.net/6/examples/collab/

**Comment by marijnh** [comment]
Added https://codemirror.net/6/examples/tooltip/

**Comment by marijnh** [comment]
Added https://codemirror.net/6/examples/panel/

**Comment by marijnh** [comment]
Added https://codemirror.net/6/examples/translate/

**Comment by marijnh** [comment]
Added https://codemirror.net/6/examples/styling/

**Comment by marijnh** [comment]
Added https://codemirror.net/6/examples/decoration/

**Comment by clansi12** [comment]
Really all are very challenging to learn the basic think. Please give a simple example, like make syntax highlighting from textarea through javascript code..
