### ISSUE TITLE
The Try link is not on every page

### ISSUE THREAD

**Issue by jdbruxelles** [codemirror/website#31]
Hi, I noticed that the link of the new Try page is not on the navigation of every page. I didn't find out how to do it so.

**Comment by marijnh** [comment]
Can you give a concrete example of a page that didn't have it? Have you tried to hard-refresh?

**Comment by jdbruxelles** [comment]
Seems to be OK on every page (without hard-refresh).

The pages concerned were:
- home
- documentation
- and some pages under `/examples/` and `/docs/`.
---
Nice Try page!
