### ISSUE TITLE
Styling bug leads to non-visible text

### ISSUE THREAD

**Issue by StoneCypher** [codemirror/website#33]
# The feature

In your collaborative editor example, `<input>` elements are transparent, allowing the bar's purple background to show through, and white text is used as accent.

![image](https://user-images.githubusercontent.com/77482/177623168-74c2f4d0-5615-499a-8e1c-e31aef678843.png)

&nbsp;

&nbsp;

&nbsp;

# The bug

The relevant `<option>`s are unstyled, and white backgrounded by default, meaning only the currently selected one is practically visible.

![image](https://user-images.githubusercontent.com/77482/177623466-5afeab34-f152-4ace-9c63-9a2312420a95.png)

![image](https://user-images.githubusercontent.com/77482/177623678-7f4083ba-dea3-4bbf-a2ac-1348f1ec6e06.png)

&nbsp;

&nbsp;

&nbsp;

# Proposed fix

I will deliver a PR which adds a rule in the site inline style block, to style the options to match the theme rather than to keep the transparent backgrounds.

![image](https://user-images.githubusercontent.com/77482/177623972-4a209381-7337-4c86-8a54-95efa08f13c6.png)

**Comment by StoneCypher** [comment]
hm, offered fix was merged but is not present on the destination site

either my inability to build caused the problem, or this isn't deployed with a merge.  i can't tell which yet

**Comment by marijnh** [comment]
Publishing is manual for the time being.

**Comment by StoneCypher** [comment]
oh gotcha
