### ISSUE TITLE
This expects to be checked out inside a (installed) codemirror/dev repository (it needs access to the sources to build the reference docs).

### ISSUE THREAD

**Issue by StoneCypher** [codemirror/website#34]
> This expects to be checked out inside a (installed) [codemirror/dev](https://github.com/codemirror/dev) repository (it needs access to the sources to build the reference docs).

Hi.  Where, please?  Git complains if you try to clone two things in the same physical location

Does this go in `%/website` ?

**Comment by StoneCypher** [comment]
do i need to `npm run build` to contribute a css rule that's embedded in a markdown document?

**Comment by marijnh** [comment]
I just ran a fresh checkout, and the website seems to build properly. This is what I did:

    git clone https://github.com/codemirror/dev cm6
    cd cm6
    bin/cm.js install
    git clone https://github.com/codemirror/website
    cd website
    npm install
    node src/index.js

**Comment by marijnh** [comment]
But for client-side-only PRs, feel free to submit them without having built them first.
