### ISSUE TITLE
update SEO docs so codemirror 5 is less prevalent in google searches

### ISSUE THREAD

**Issue by vincentvandijck** [codemirror/website#38]
**Steps to reproduce:**

1. google 'CodeMirror docs'
2. press first link

**Expected behavior:**

Arrive at most recent up-to-date documentation

**Resulted behavior:**

Arrive at https://codemirror.net/5/doc/manual.html , the documentation pointing towards the previous version.

**Comments:** 

It is unclear from reading the google search result to which CodeMirror the link is pointing to. As it is unclear from the docs which parts of the API are deprecated and which parts aren't, I have no valuable information to find on this link. So it is a bit a 50/50 chance everytime I google for the CodeMirror-docs.

**Comment by vincentvandijck** [comment]
Mmm, I am not an SEO-expert by any means.
But let's look a bit at the current situation:

![image](https://user-images.githubusercontent.com/10504064/179814342-77258bf3-a56d-4ce0-be72-85494daf3e26.png)

The top one has as its url https://codemirror.net/doc/manual which redirects to https://codemirror.net/5/doc/manual.html (in reality https://codemirror.net/doc/manual 404s, it needs to be https://codemirror.net/doc/manual.html, but s just a google-thing i guess).
The second link leads to https://codemirror.net/docs which is the up-to-date reference point.

I think a good first step would be just to always mention the version number in the title/description of your docs.
Secondly, I wonder if it still makes sense to redirect the https://codemirror.net/doc to https://codemirror.net/5/doc 
Maybe just removing this redirection could solve the issue?

**Comment by marijnh** [comment]
> Maybe just removing this redirection could solve the issue?

That would break a _lot_ of existing links, so I don't want to do that.

I've added '5' to the title of the old manual and front page, but I can't find anything about intentionally reducing a page's search ranking. Engines will eventually pick up that more links are being created to the new docs, but that might take a while.

**Comment by vincentvandijck** [comment]
> That would break a lot of existing links, so I don't want to do that.

I completely understand that.
Thank you, I really appreciate the effort!
Having the version number in the title will already solve 99% of the confusion, I think.

I see that the updated title does not appear yet in Google. Google will have to recrawl it, which might happen automatically at some point, but you could also request a recrawl https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl
