### ISSUE TITLE
description in examples/collab hard to understand

### ISSUE THREAD

**Issue by xuxucode** [codemirror/website#43]
[LINK](https://codemirror.net/examples/collab/#:~:text=If%20confirming%20local%20changes%20only%20happened%20on%20pull)
> The reason local updates are confirmed through the same mechanism as remote updates is that we want to handle the case where the push request successfully arrives at the authority, but the network fails before the response comes back to the peer. If confirming local changes only happened on **pull**, it would be hard to resynchronize with the authority after such an event.

In this "If confirming local changes only happened on **pull**" sentence, do you actually mean "push" rather than "pull"? "push" makes sense to me.

**Comment by marijnh** [comment]
You are entirely right, that should say 'push'. Attached patch corrects it.
