### ISSUE TITLE
non-editable javascript editor at top of home page

### ISSUE THREAD

**Issue by stevegt** [codemirror/website#45]
At the moment, https://codemirror.net/ has this text near the top:

```
This is a CodeMirror field, configured for editing JavaScript code.
```

Is that text supposed to be in or under an editable field?  On my platform there's nothing editable there.  It's being rendered as:

```
<div id=editor></div>

<p>This is a CodeMirror field, configured for editing JavaScript code.</p>
```

Chrome 101.0.4951.54 on Linux

**Comment by marijnh** [comment]
Thanks for spotting that. A website rebuild had gone wrong and the demo editor was broken—fixed now.
