### ISSUE TITLE
Spelled theme wrong.

### ISSUE THREAD

**Issue by Alien10123** [codemirror/website#55]
On the [extensions docs page](https://codemirror.net/docs/extensions/), if you go under the sub-heading "Presentation", then go on the line under the sub-sub-heading "Styling", theme is spelt wrong. In [this file](https://github.com/codemirror/website/blob/master/site/docs/extensions/index.html) it is on line 60 just before the brackets.

**Comment by marijnh** [comment]
Thanks for spotting that. Corrected in 8f3df85
