### ISSUE TITLE
Zebra Stripes Example is broken

### ISSUE THREAD

**Issue by lpellegr** [codemirror/website#6]
Page:
https://codemirror.net/6/examples/zebra/

Console error:
> codemirror.js:530 Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.ͼ1 zebraStripe@light {background-color: #f4fafa;}'.
>     at StyleSet.mount (https://codemirror.net/6/codemirror.js:530:139)
>     at Function.mount (https://codemirror.net/6/codemirror.js:529:60)
>     at EditorView.mountStyles (https://codemirror.net/6/codemirror.js:1123:784)
>     at new EditorView (https://codemirror.net/6/codemirror.js:1093:803)
>     at https://codemirror.net/6/examples/zebra/zebra.js:7:218
>     at https://codemirror.net/6/examples/zebra/zebra.js:7:426

**Comment by marijnh** [comment]
Good point—I didn't check the examples against the 0.15 changes. Others were broken as well. Should be better now.
