### ISSUE TITLE
Split View documentation - Typescript: Expected 0 type arguments, but got 1.

### ISSUE THREAD

**Issue by nicholasbulka** [codemirror/website#8]
Typescript error:
TS2558: Expected 0 type arguments, but got 1.
      
`let syncAnnotation = Annotation.define<boolean>()`

removing `<boolean>` worked, 
`let syncAnnotation = Annotation.define()`

I'm not sure how to put in a PR for the documentation, or if this is just specific to a certain tsconfig I'm running and might help someone in the future.

**Comment by marijnh** [comment]
Going to close this until it comes up in a way that I can reproduce.
